### ISSUE TITLE
Use proper model loading

### ISSUE THREAD

**Issue by me4502** [EngineHub/SchematicWebViewer#1]
https://minecraft.gamepedia.com/Model

This describes how models are loaded by the game, for textures and locations.

**Comment by octylFractal** [comment]
I presume this might be an extension of this bug:
![Screenshot_20200207_190017](https://user-images.githubusercontent.com/2093023/74078207-3770e600-49dc-11ea-82fc-2b91b1f3100d.png)
Tried to render a chest.

**Comment by me4502** [comment]
Fixed by https://github.com/EngineHub/SchematicWebViewer/pull/8
