### ISSUE TITLE
Allow for enabling transparent canvas

### ISSUE THREAD

**Issue by McJeffr** [EngineHub/SchematicWebViewer#10]
Right now, the background color of the canvas is white. This is acceptable in most use-cases, though in some others it might be useful to set the background color to something that is not white. Use cases for this could be a dark-mode of a website that makes use of this library, or a shade of gray when on a card of some sort.

In order to deal with all possible cases, either one of the following options could work:
- Allowing users to set the background color to something else than white
- Allowing users to remove the background altogether, relying on the background of the component the canvas is rendered in
- A combination of both

Since removing the background might affect performance, allowing the user to set their own background might be the best solution for performance. But if performance is not so important for the user, removing the background color might be a better solution.

I will see about creating a PR for this later this week.

**Comment by me4502** [comment]
Added in 31f8e2e97046751bee21da1344eb676001669a95
