### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by bdubois06** [EngineHub/SchematicWebViewer#19]
Hi, I have this error when I try to load my schem file :
`Uncaught (in promise) ReferenceError: Buffer is not defined
    at parseNbt (utils.js:34:1)
    at Module.<anonymous> (renderer.js:103:1)
    at Generator.next (<anonymous>)
    at renderer.js:29:1
    at new Promise (<anonymous>)
    at __awaiter (renderer.js:8:1)
    at Module.renderSchematic (renderer.js:59:1)
    at index.js:64:1
    at commitHookEffectListMount (react-dom.development.js:19607:1)
    at commitPassiveHookEffects (react-dom.development.js:19644:1)`

![image](https://user-images.githubusercontent.com/70747894/188168093-9cbbfa00-2bb0-49b6-a325-77df8d827a36.png)

**Comment by me4502** [comment]
If you're running it in some browsers you'll likely need a Buffer polyfill, you can get the buffer package from npm for that

**Comment by Weefle** [comment]
Thanks for your fast response but I'm not so good in React, do I need to use webpack to do so ?
Some people say to add this to their webpack config which I'm not using:
![image](https://user-images.githubusercontent.com/18496043/188263514-08823a41-51a2-466e-be62-55a1e22b6395.png)
Also, I'm the same person, sorry, I used my pro account yesterday.

**Comment by me4502** [comment]
No, it doesn't need anything special.

I've included this within the dependencies of the project in 4.3.1; https://github.com/EngineHub/SchematicWebViewer/commit/4c378e73ea91873b38fdebee8423289e7c5d02fc

**Comment by ItsMCB** [comment]
I'm coming across this issue (`Uncaught (in promise) ReferenceError: Buffer is not defined`) with the latest version. I'm attempting to add a schematic preview to my website using the Astro framework. I'm using version `4.8.1`. I wonder if I'm missing an Astro setting to bundle the Buffer dependency with the site.
