### ISSUE TITLE
Error when trying to load it from jsDelivr

### ISSUE THREAD

**Issue by Weefle** [EngineHub/SchematicWebViewer#23]
Uncaught SyntaxError: The requested module '/npm/babylonjs@5.18.0/+esm' does not provide an export named 'Axis' (at index.js:1:1)

**Comment by me4502** [comment]
This looks like something you'd have to report to BabylonJS, it looks like the issue you're hitting is from their package rather than ours

**Comment by Weefle** [comment]
Thanks for the fast answer, I'll try this.
Here is the error line by the way:
![image](https://github.com/EngineHub/SchematicWebViewer/assets/18496043/05c6130d-8edf-495c-ad4a-7612edb1a3ec)

**Comment by Weefle** [comment]
Replaced the import 'babylonjs' by '@babylonjs/core' everywhere in the project and everything is working fine.

**Comment by me4502** [comment]
We've made that same change now to improve tree shaking, so presumably this issue should be fixed now.
